name: Python CI

# on: Inicio del Evento
on:
  push:
    branches:
      - feature/PA-23
      - feature/PA-7
      - feature/PA-13
      - feature/HUS-PA-20
      - feature/PA-112
      - feature/PA-42
 
# Definir los Jobs
jobs:
  build-feature:
    runs-on: ubuntu-latest

    steps:   
    - name: Checkout código fuente
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Instalar dependencias
      run: pip install -r gestion_empresas/requirements.txt

    - name: Ejecutar pruebas unitarias
      run: python -m unittest discover gestion_empresas/tests

    - name: Ejecutar pruebas unitarias con covertura
      run: |
        coverage run -m unittest discover -s gestion_empresas/tests -p 'test_*.py'
        coverage report -m --fail-under=50

    - name: Finalizar flujo de trabajo
      run: echo "El flujo de trabajo se ha completado exitosamente."